[package]
name = "rust-challenge"
version = "0.1.0"
authors = ["uesud <uesud@live.jp>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.6"